version: 2
updates:
  # Check for NuGet updates in the core application project
  - package-ecosystem: "nuget"
    directory: "/logindirector"
    schedule:
      interval: "weekly"
      day: "sunday"

  # Check for NuGet updates in the unit test project
  - package-ecosystem: "nuget"
    directory: "/LoginDirectorTests"
    schedule:
      interval: "weekly"
      day: "sunday"