name: login director - trigger CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
         dotnet-version: 5.0.x
 
    - name: Restore
      run: dotnet restore
      working-directory: ./logindirector
 
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./logindirector
 
    - name: Test
      run: dotnet test --no-restore
      working-directory: ./logindirector

    # - name: Publish
    #   run: dotnet publish ${{ github.workspace }}/src/WebApp1/WebApp1.csproj
    
    # - name: Upload Build Artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: WebApp1
    #     path: ${{ github.workspace }}/src/WebApp1/bin/Debug/netcoreapp3.1/publish/
    #   test
        
