<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.4.1" />
    <PackageReference Include="MSTest.TestFramework" Version="4.4.1" />
    <PackageReference Include="coverlet.collector" Version="10.0.1"><IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
<PrivateAssets>all</PrivateAssets>
</PackageReference>
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="Newtonsoft.Json" Version="14.0.1-beta2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\logindirector.csproj" />
  </ItemGroup>
</Project>
