name: login director - build on PR and deploy on PR merged (pushed)

on:
  push:
    branches: [develop, staging, main]
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"
  pull_request:
    types: [closed, opened, synchronize]
    branches: [develop, staging, main]
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"

jobs:
  build:
  
    runs-on: ubuntu-latest

    env:
      # Disable sending usage data to Microsof
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      # Stop wasting time caching packages
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0

    steps:
      - name: Checking your input
        run: |
          echo "github.event.pull_request.merged           : $MERGED_RAW"
          echo "github.event.pull_request.merged  == true  : $MERGED_TRUE_BOOL"
        env:
          MERGED_RAW: ${{ github.event.pull_request.merged }}
          MERGED_TRUE_BOOL: ${{ github.event.pull_request.merged == true }}
      - uses: actions/checkout@v2

      - name: Check output
        run: echo ${{ github.base_ref }}
      
      - name: Setup .NET v5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.412

      - name: Restore
        run: dotnet restore ${{ github.workspace }}/logindirector/logindirector.csproj

      - name: Build
        run: dotnet build ${{ github.workspace }}/logindirector/logindirector.csproj --configuration Release --no-restore
        #working-directory: ./logindirector

      - name: Test
        run: dotnet test ${{ github.workspace }}/logindirector/logindirector.csproj --no-restore
        #working-directory: ./logindirector

      - name: Publish
        run: dotnet publish ${{ github.workspace }}/logindirector/logindirector.csproj

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.base_ref }}-deploymentArchive
          path: ${{ github.workspace }}/logindirector/bin/Debug/net6.0/publish/

  deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    needs: build

    env:
      # Disable sending usage data to Microsof
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      # Stop wasting time caching packages
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
    
    steps:
      - run: echo PR #${{ github.event.number }} has been merged
      - uses: actions/checkout@v2

      - name: Check output
        run: echo ${{ github.base_ref }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.412

      - name: Download artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: ${{ github.base_ref}}-deploymentArchive
          path: ${{ github.workspace }}/logindirector/bin/Release/net6.0/publish/

      - name: Deploy to Cloud Foundry - development
        id: cf_dev
        if: ${{ github.base_ref == 'develop' }}
        uses: jhunt/cf-push@v1
        with:
          api: ${{ secrets.CF_API }}
          org: ${{ secrets.CF_ORG }}
          space: ${{ secrets.CF_SPACE_DEVELOPMENT  }}
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          manifest: manifest/manifest_dev.yml
          validate: false

      # - name: Cloudfoundry Dev deployment result
      #   if: ${{ github.base_ref == 'develop' }}
      #   run: echo "Deployment was ${{ steps.cf_dev.outputs.deploymentResult }}

      - name: Deploy to Cloud Foundry - staging / testing
        id: cf_stage
        if: ${{ github.base_ref == 'staging' }}
        uses: jhunt/cf-push@v1
        with:
          api: ${{ secrets.CF_API }}
          org: ${{ secrets.CF_ORG }}
          space: ${{ secrets.CF_SPACE_STAGING  }}
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          manifest: manifest/manifest_staging.yml
          validate: false

      # - name: Cloudfoundry Test deployment result
      #   if: ${{ github.base_ref == 'staging' }}
      #   run: echo "Deployment was ${{ steps.cf_stage.outputs.deploymentResult }}

      - name: Deploy to Cloud Foundry - production
        id: cf_prod
        if: ${{ github.base_ref == 'main' }}
        uses: jhunt/cf-push@v1
        with:
          api: ${{ secrets.CF_API }}
          org: ${{ secrets.CF_ORG }}
          space: ${{ secrets.CF_SPACE_PRODUCTION  }}
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          manifest: manifest/manifest_prod.yml
          validate: false

      # - name: Cloudfoundry Prod deployment result
      #   if: ${{ github.base_ref == 'main' }}
      #   run: echo "Deployment was ${{ steps.cf_prod.outputs.deploymentResult }}

  # close_job:
  #   # this job will only run if the PR has been closed without being merged
  #   if: github.event.pull_request.merged != false
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: |
  #       echo PR #${{ github.event.number }} has been closed without being merged
