name: login director - trigger CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      # Disable sending usage data to Microsof
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      # Stop wasting time caching packages
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET v5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.400
      # - name: Copy manifest.yaml
      #   run: cp ./manifest.yaml ${{ github.workspace }}/logindirector/bin/Debug/net5.0/publish/

      - name: Restore
        run: dotnet restore ${{ github.workspace }}/logindirector/logindirector.csproj

      - name: Build
        run: dotnet build ${{ github.workspace }}/logindirector/logindirector.csproj --configuration Release --no-restore
        #working-directory: ./logindirector

      - name: Test
        run: dotnet test ${{ github.workspace }}/logindirector/logindirector.csproj --no-restore
        #working-directory: ./logindirector

      - name: Publish
        run: dotnet publish ${{ github.workspace }}/logindirector/logindirector.csproj

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: deploymentArchive
          path: ${{ github.workspace }}/logindirector/bin/Debug/netcoreapp3.1/publish/

  deploy:

    needs: build


    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.400


      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: deploymentArchive

      - name: Deploy to Cloud Foundry
        uses: jhunt/cf-push@v1
        with:
          api:      ${{ secrets.CF_API }}
          org:      ${{ secrets.CF_ORG }}
          space:    ${{ secrets.CF_SPACE_DEVELOPMENT  }}
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          manifest: manifest.yml
          validate: false